[window]
decorations = "buttonless"
opacity = 0.85
blur = true

[window.padding]
x = 10
y = 10

[font]
size = 14.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 2

[cursor]
style = "Beam"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black   = "0x15161e"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xa9b1d6"

[colors.bright]
black   = "0x414868"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xc0caf5"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"

[terminal]
